apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-app-deployment
  namespace: default
  labels:
    app: go-hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-app
  template:
    metadata:
      labels:
        app: go-hello-app
    spec:
      containers:
      - name: go-hello-app
        image: go-hello-app:v1
        ports:
        - containerPort: 8080
          name: http
