apiVersion: v1
kind: Service
metadata:
  name: go-hello-app-service
  namespace: default
  labels:
    app: go-hello-app
spec:
  selector:
    app: go-hello-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
